version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
    pre_build:
        commands:
            - pip install -r requirements-test.txt -t .
    build:
        commands:
            - PYTHONPATH=./src AGE_RESTRICTION=28 python -m pytest tests