version: 0.2
phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
            - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    build:
        commands:
            - TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker build -t $REPOSITORY:$TAG .
            - docker tag $REPOSITORY:$TAG $REPOSITORY_URI:latest
    post_build:
        commands:
            - docker push $REPOSITORY_URI:latest